apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: _ignored_
spec:
  desiredState:
    dns-resolver:
      config:
        search: []
        server: []
    routes:
      config:
    interfaces:
  nodeSelector:
    kubernetes.io/hostname: _replaced_
    node-role.kubernetes.io/worker: ""
