apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

transformers:
# Set namespace to OpenStack on all namespaced objects without a namespace
- |-
  apiVersion: builtin
  kind: NamespaceTransformer
  metadata:
    name: _ignored_
    namespace: openstack
  setRoleBindingSubjects: none
  unsetOnly: true
  fieldSpecs:
  - path: metadata/name
    kind: Namespace
    create: true

components:
  - ../../components/nncp

patches:
  - target:
      kind: NodeNetworkConfigurationPolicy
      name: node-0
    path: patch.yaml
  - target:
      kind: NodeNetworkConfigurationPolicy
      name: node-1
    path: patch.yaml
  - target:
      kind: NodeNetworkConfigurationPolicy
      name: node-2
    path: patch.yaml

    #resources:
    #  - values.yaml
    #


